version: '3'
services:
  quote-back:
    build: ./QuoteStack-back
    volumes:
      - .env:/var/www/.env
    command:  sh -c "php artisan serve --host 0.0.0.0"

  quote-front:
    build: ./QuoteStack-front
    depends_on:
      - quote-back

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - quote-back
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf


volumes:
  laravel-volume: