version: '3'
services:
  quote-back:
    build: ./QuoteStack-back
    volumes:
      - ./QuoteStack-back:/var/www
    command:  sh -c "php artisan serve --host 0.0.0.0"

  quote-front:
    build: ./QuoteStack-front
    volumes:
      - ./QuoteStack-front:/tmp/app
    command:  sh -c "yarn install && yarn start"
    depends_on:
      - quote-back

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
     - quote-back
     - quote-front
    volumes:
      - ./reverse_proxy_dev.conf:/etc/nginx/conf.d/default.conf

  